blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/platformplatform/PlatformPlatform/discussions/new/choose
    about: Start a new discussion on our GitHub Community pages
  - name: Browse existing discussions
    url: https://github.com/platformplatform/PlatformPlatform/discussions
    about: Visit our GitHub Community pages to view existing discussions (or click Discussions in the menu)
